In [2]:
from aquire_zillow import get_connection
from aquire_zillow import get_zillow_data

In [5]:
#test the functions and put zillow data into dataframe
zillow_df=get_zillow_data()

In [6]:
zillow_df.head()

,basementsqft,bathroomcnt,bedroomcnt,calculatedbathnbr,finishedfloor1squarefeet,calculatedfinishedsquarefeet,finishedsquarefeet12,finishedsquarefeet13,finishedsquarefeet15,finishedsquarefeet50,...,censustractandblock,logerror,transactiondate,year,propertylandusedesc,storydesc,typeconstructiondesc,airconditioningdesc,buildingclassdesc,heatingorsystemdesc
0,NaN,2.0,3.0,2.0,NaN,1684.0,1684.0,NaN,NaN,NaN,...,6.037107e+13,0.0276,2016-01-01,2016,Single Family Residential,None,None,Central,None,Central
1,NaN,3.5,4.0,3.5,NaN,2263.0,2263.0,NaN,NaN,NaN,...,NaN,-0.1684,2016-01-01,2016,Single Family Residential,None,None,None,None,None
2,NaN,3.0,2.0,3.0,NaN,2217.0,2217.0,NaN,NaN,NaN,...,6.037464e+13,-0.0040,2016-01-01,2016,Single Family Residential,None,None,Central,None,Central
3,NaN,2.0,2.0,2.0,NaN,839.0,839.0,NaN,NaN,NaN,...,6.037296e+13,0.0218,2016-01-02,2016,Condominium,None,None,Central,None,Central
4,NaN,2.5,4.0,2.5,NaN,2283.0,2283.0,NaN,NaN,NaN,...,6.059042e+13,-0.0050,2016-01-02,2016,Single Family Residential,None,None,None,None,None